### ISSUE TITLE
administrator rolename is not used as expected

### ISSUE THREAD

**Issue by bodsch** [bodsch/ansible-role-harbor#14]
```
harbor_users:
  - username: automatic
    password: "{{ vault__harbor_automatic }}"
    email: automatic@matrix.lan
    realname: automatic build
    role_name: administrator
    has_admin_role: false
```
