### ISSUE TITLE
No default scanner

### ISSUE THREAD

**Issue by patsevanton** [bodsch/ansible-role-harbor#9]
Hello! Thanks for role harbor
I installed harbor, but don`t have scanner.
How install scanner by this role?
Playbook
```
- hosts: harbor
  become: true
  roles:
    - role: systemli.letsencrypt

- hosts: harbor
  become: yes
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
    - name: install pip3
      apt: name=python3-pip state=present
    - name: Install multi python packages
      pip:
        name:
          - docker
          - docker-compose
  roles:
    - role: geerlingguy.docker
    - role: ansible-role-harbor
```

Inventory
```
all:
  children:
    harbor:
      hosts:
        "harbor":
          ansible_host: "xxx"
  vars:
    letsencrypt_opts_extra: "--register-unsafely-without-email"
    letsencrypt_cert:
      name: harbor.xxx.sslip.io
      domains:
        - harbor.xxx.sslip.io
      challenge: http
      http_auth: standalone
      reuse_key: True
    harbor_ui_url_protocol: https
    harbor_admin_password: superpassword
    harbor_hostname: harbor.xxx.sslip.io
    harbor_ssl_cert: /etc/letsencrypt/live/harbor.xxx.sslip.io/cert.pem
    harbor_ssl_cert_key: /etc/letsencrypt/live/harbor.xxx.sslip.io/privkey.pem
    harbor_extras:
    - clair
    - notary
```

![image](https://user-images.githubusercontent.com/10828883/165329460-67b6904a-63e2-42d5-b8f4-436dd2acece0.png)
